#Generated by ChatGPT
#Dockerfile


# -------------------------
# Stage 1: Build
# -------------------------
    FROM node:20-alpine AS builder

    WORKDIR /app
    
    # Copy package files
    COPY package.json package-lock.json* ./
    
    RUN npm ci 
    
    # Copy Prisma schema (if using Prisma)
    COPY prisma ./prisma/
    # Generate Prisma client
    RUN npx prisma generate
    
    # Copy the rest of the application code
    COPY . .
    
    # Build the Next.js application
    RUN npm run build
    
    # -------------------------
    # Stage 2: Production
    # -------------------------
    FROM node:20-alpine
    
    WORKDIR /app
    
    # Copy node_modules and the built app from builder
    COPY --from=builder /app/node_modules ./node_modules
    COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
    COPY --from=builder /app/.next ./.next
    COPY --from=builder /app/public ./public
    COPY --from=builder /app/package.json ./package.json
    COPY --from=builder /app/prisma ./prisma/
    COPY --from=builder /app/public ./public
    COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
    COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

    RUN mkdir -p /app/.next/server/app/api/bookings/pdf/data && \
    cp -r /app/node_modules/pdfkit/js/data/* /app/.next/server/app/api/bookings/pdf/data/
    
    EXPOSE 3000
    
    # Start the Next.js production server
    CMD ["npm", "start"]
    